# Generated by Django 4.0.4 on 2022-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.PositiveIntegerField(max_length=12, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('url', models.URLField(max_length=2048)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
