# Generated by Django 4.0.4 on 2022-05-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telegram', '0005_telegramuser_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='hash',
        ),
    ]
